export type AnyEnum = |
	Command |
	Producer |
	Consumer |
	Version |
	Lock |
	LogCategory |
	Chroma |
	LogLevel |
	Transition |
	Direction |
	BlendMode |
	Ease |
	ChannelFormat |
	ChannelLayout

/**
 *
 */
export enum Command {
	LOADBG = 'LOADBG',
	LOAD = 'LOAD',
	PLAY = 'PLAY',
	PAUSE = 'PAUSE',
	RESUME = 'RESUME',
	STOP = 'STOP',
	CLEAR = 'CLEAR',
	CALL = 'CALL',
	SWAP = 'SWAP',
	ADD = 'ADD',
	REMOVE = 'REMOVE',
	PRINT = 'PRINT',
	LOG_LEVEL = 'LOG LEVEL',
	LOG_CATEGORY = 'LOG CATEGORY',
	SET = 'SET',
	LOCK = 'LOCK',
	DATA_STORE = 'DATA STORE',
	DATA_RETRIEVE = 'DATA RETRIEVE',
	DATA_LIST = 'DATA LIST',
	DATA_REMOVE = 'DATA REMOVE',
	CG_ADD = 'CG ADD',
	CG_PLAY = 'CG PLAY',
	CG_STOP = 'CG STOP',
	CG_NEXT = 'CG NEXT',
	CG_REMOVE = 'CG REMOVE',
	CG_CLEAR = 'CG CLEAR',
	CG_UPDATE = 'CG UPDATE',
	CG_INVOKE = 'CG INVOKE',
	CG_INFO = 'CG INFO',
	MIXER_KEYER = 'MIXER KEYER',
	MIXER_CHROMA = 'MIXER CHROMA',
	MIXER_BLEND = 'MIXER BLEND',
	MIXER_OPACITY = 'MIXER OPACITY',
	MIXER_BRIGHTNESS = 'MIXER BRIGHTNESS',
	MIXER_SATURATION = 'MIXER SATURATION',
	MIXER_CONTRAST = 'MIXER CONTRAST',
	MIXER_LEVELS = 'MIXER LEVELS',
	MIXER_FILL = 'MIXER FILL',
	MIXER_CLIP = 'MIXER CLIP',
	MIXER_ANCHOR = 'MIXER ANCHOR',
	MIXER_CROP = 'MIXER CROP',
	MIXER_ROTATION = 'MIXER ROTATION',
	MIXER_PERSPECTIVE = 'MIXER PERSPECTIVE',
	MIXER_MIPMAP = 'MIXER MIPMAP',
	MIXER_VOLUME = 'MIXER VOLUME',
	MIXER_MASTERVOLUME = 'MIXER MASTERVOLUME',
	MIXER_STRAIGHT_ALPHA_OUTPUT = 'MIXER STRAIGHT_ALPHA_OUTPUT',
	MIXER_GRID = 'MIXER GRID',
	MIXER_COMMIT = 'MIXER COMMIT',
	MIXER_CLEAR = 'MIXER CLEAR',
	CHANNEL_GRID = 'CHANNEL_GRID',
	THUMBNAIL_LIST = 'THUMBNAIL LIST',
	THUMBNAIL_RETRIEVE = 'THUMBNAIL RETRIEVE',
	THUMBNAIL_GENERATE = 'THUMBNAIL GENERATE',
	THUMBNAIL_GENERATE_ALL = 'THUMBNAIL GENERATE_ALL',
	CINF = 'CINF',
	CLS = 'CLS',
	FLS = 'FLS',
	TLS = 'TLS',
	VERSION = 'VERSION',
	INFO = 'INFO',
	INFO_TEMPLATE = 'INFO TEMPLATE',
	INFO_CONFIG = 'INFO CONFIG',
	INFO_PATHS = 'INFO PATHS',
	INFO_SYSTEM = 'INFO SYSTEM',
	INFO_SERVER = 'INFO SERVER',
	INFO_QUEUES = 'INFO QUEUES',
	INFO_THREADS = 'INFO THREADS',
	INFO_DELAY = 'INFO DELAY',
	DIAG = 'DIAG',
	GL_INFO = 'GL INFO',
	GL_GC = 'GL GC',
	BYE = 'BYE',
	KILL = 'KILL',
	RESTART = 'RESTART',
	HELP = 'HELP',
	HELP_PRODUCER = 'HELP PRODUCER',
	HELP_CONSUMER = 'HELP CONSUMER'
}

/**
 *
 */
export enum Producer {
	FFMPEG = 'FFmpeg Producer',
	DECKLINK = 'Decklink Producer',
	HTML = 'HTML Producer',
	PSD = 'PSD Scene Producer',
	FLASH = 'Flash Producer (.ft)',
	FLASH_CT = 'Flash Producer (.ct)',
	FLASH_SWF = 'Flash Producer (.swf)',
	IMAGE_SCROLL = 'Image Scroll Producer',
	IMAGE = 'Image Producer',
	REROUTE = 'Reroute Producer',
	TEXT = 'Text Producer',
	SCENE = 'XML Scene Producer',
	COLOR = 'Color Producer'
}

/**
 *
 */
export enum Consumer {
	FFMPEG = 'FFMpeg Consumer',
	STREAMING = 'Streaming Consumer',
	ADUIO = 'System Audio Consumer',
	BLUEFISH = 'Bluefish Consumer',
	DECKLINK = 'Decklink Consumer',
	SCREEN = 'Screen Consumer',
	IVGA = 'iVGA Consumer',
	IMAGE = 'Image Consumer'
}

/**
 *
 *
 */
export enum Version {
	SERVER = 'SERVER',
	FLASH = 'FLASH',
	TEMPLATEHOST = 'TEMPLATEHOST',
	CEF = 'CEF'
}

/**
 *
 *
 */
export enum Lock {
	ACQUIRE = 'ACQUIRE',
	RELEASE = 'RELEASE',
	CLEAR = 'CLEAR'
}

/**
 *
 *
 */
export enum LogCategory {
	CALLTRACE = 'CALLTRACE',
	COMMUNICATION = 'COMMUNICATION'
}

/**
 *
 *
 */
export enum Chroma {
	NONE = 'NONE',
	GREEN = 'GREEN',
	BLUE = 'BLUE'
}

/**
 *
 *
 */
export enum LogLevel {
	TRACE = 'TRACE',
	DEBUG = 'DEBUG',
	INFO = 'INFO',
	WARNING = 'WARNING',
	ERROR = 'ERROR',
	FATAL = 'FATAL'	// @todo: 2.1?????
}

/**
 *
 *
 */
export enum Transition {
	CUT = 'CUT',
	MIX = 'MIX',
	PUSH = 'PUSH',
	WIPE = 'WIPE',
	SLIDE = 'SLIDE',
	STING = 'STING'
}

/**
 *
 *
 */
export enum Direction {
	LEFT = 'LEFT',
	RIGHT = 'RIGHT'
}

/**
 *
 */
export enum BlendMode {
	NORMAL = 'NORMAL',
	LIGHTEN = 'LIGHTEN',
	DARKEN = 'DARKEN',
	MULTIPLY = 'MULTIPLY',
	AVERAGE = 'AVERAGE',
	ADD = 'ADD',
	SUBTRACT = 'SUBTRACT',
	DIFFERENCE = 'DIFFERENCE',
	NEGATION = 'NEGATION',
	EXCLUSION = 'EXCLUSION',
	SCREEN = 'SCREEN',
	OVERLAY = 'OVERLAY',
	SOFT_LIGHT = 'SOFT LIGHT',
	HARD_LIGHT = 'HARD LIGHT',
	COLOR_DODGE = 'COLOR DODGE',
	COLOR_BURN = 'COLOR BURN',
	LINEAR_DODGE = 'LINEAR DODGE',
	LINEAR_BURN = 'LINEAR BURN',
	LINEAR_LIGHT = 'LINEAR LIGHT',
	VIVID_LIGHT = 'VIVID LIGHT',
	PIN_LIGHT = 'PIN LIGHT',
	HARD_MIX = 'HARD MIX',
	REFLECT = 'REFLECT',
	GLOW = 'GLOW',
	PHOENIX = 'PHOENIX',
	CONTRAST = 'CONTRAST',
	SATURATION = 'SATURATION',
	COLOR = 'COLOR',
	LUMINOSITY = 'LUMINOSITY'
}

/**
 *
 */
export enum Ease {
	LINEAR = 'LINEAR',
	NONE = 'EASENONE',
	IN_QUAD = 'EASEINQUAD',
	OUT_QUAD = 'EASEOUTQUAD',
	IN_OUT_QUAD = 'EASEINOUTQUAD',
	OUT_IN_QUAD = 'EASEOUTINQUAD',
	IN_CUBIC = 'EASEINCUBIC',
	OUT_CUBIC = 'EASEOUTCUBIC',
	IN_OUT_CUBIC = 'EASEINOUTCUBIC',
	OUT_IN_CUBIC = 'EASEOUTINCUBIC',
	IN_QUART = 'EASEINQUART',
	OUT_QUART = 'EASEOUTQUART',
	IN_OUT_QUART = 'EASEINOUTQUART',
	OUT_IN_QUART = 'EASEOUTINQUART',
	IN_QUINT = 'EASEINQUINT',
	OUT_QUINT = 'EASEOUTQUINT',
	IN_OUT_QUINT = 'EASEINOUTQUINT',
	OUT_IN_QUINT = 'EASEOUTINQUINT',
	IN_SINE = 'EASEINSINE',
	OUT_SINE = 'EASEOUTSINE',
	IN_OUT_SINE = 'EASEINOUTSINE',
	OUT_IN_SINE = 'EASEOUTINSINE',
	IN_EXPO = 'EASEINEXPO',
	OUT_EXPO = 'EASEOUTEXPO',
	IN_OUT_EXPO = 'EASEINOUTEXPO',
	OUT_IN_EXPO = 'EASEOUTINEXPO',
	IN_CIRC = 'EASEINCIRC',
	OUT_CIRC = 'EASEOUTCIRC',
	IN_OUT_CIRC = 'EASEINOUTCIRC',
	OUT_IN_CIRC = 'EASEOUTINCIRC',
	IN_ELASTIC = 'EASEINELASTIC',
	OUT_ELASTIC = 'EASEOUTELASTIC',
	IN_OUT_ELASTIC = 'EASEINOUTELASTIC',
	OUT_IN_ELASTIC = 'EASEOUTINELASTIC',
	IN_BACK = 'EASEINBACK',
	OUT_BACK = 'EASEOUTBACK',
	IN_OUT_BACK = 'EASEINOUTBACK',
	OUT_IN_BACK = 'EASEOUTINTBACK',
	OUT_BOUNCE = 'EASEOUTBOUNCE',
	IN_BOUNCE = 'EASEINBOUNCE',
	IN_OUT_BOUNCE = 'EASEINOUTBOUNCE',
	OUT_IN_BOUNCE = 'EASEOUTINBOUNCE'
}

/**
 *
 */
export enum ChannelFormat {
	INVALID = 'invalid',
	PAL = 'PAL',
	NTSC = 'NTSC',
	SD_576P2500 = '576p2500',
	HD_720P2398 = '720p2398',
	HD_720P2400 = '720p2400',
	HD_720P2500 = '720p2500',
	HD_720P5000 = '720p5000',
	HD_720P2997 = '720p2997',
	HD_720P5994 = '720p5994',
	HD_720P3000 = '720p3000',
	HD_720P6000 = '720p6000',
	HD_1080P2398 = '1080p2398',
	HD_1080P2400 = '1080p2400',
	HD_1080I5000 = '1080i5000',
	HD_1080I5994 = '1080i5994',
	HD_1080I6000 = '1080i6000',
	HD_1080P2500 = '1080p2500',
	HD_1080P2997 = '1080p2997',
	HD_1080P3000 = '1080p3000',
	HD_1080P5000 = '1080p5000',
	HD_1080P5994 = '1080p5994',
	HD_1080P6000 = '1080p6000',
	UHD_1556P2398 = '1556p2398',
	UHD_1556P2400 = '1556p2400',
	UHD_1556P2500 = '1556p2500',
	DCI_1080P2398 = 'dci1080p2398',
	DCI_1080P2400 = 'dci1080p2400',
	DCI_1080P2500 = 'dci1080p2500',
	UHD_2160P2398 = '2160p2398',
	UCH_2160P2400 = '2160p2400',
	UHD_2160P2500 = '2160p2500',
	UHD_2160P2997 = '2160p2997',
	UHD_2160P3000 = '2160p3000',
	UHD_2160P5000 = '2160p5000',
	UHD_2160P5994 = '2160p5994',
	UHD_2160P6000 = '2160p6000',
	DCI_2160P2398 = 'dci2160p2398',
	DCI_2160P2400 = 'dci2160p2400',
	DCI_2160P2500 = 'dci2160p2500'
}

/**
 *
 */
export enum ChannelLayout {

}
